flex lexical.l
bison -d syntaxe.y
gcc lex.yy.c syntaxe.tab.c -lfl -ly -o EasyCode
@echo off
REM Compile the lexical analyzer with FLEX
flex lexical.l
if %errorlevel% neq 0 (
    echo [ERROR] Failed to compile lexical.l with FLEX.
    pause
    exit /b %errorlevel%
)

REM Compile the syntax analyzer with BISON
bison -d syntaxe.y
if %errorlevel% neq 0 (
    echo [ERROR] Failed to compile syntaxe.y with BISON.
    pause
    exit /b %errorlevel%
)

REM Compile the C code generated by FLEX and BISON
gcc lex.yy.c syntaxe.tab.c -o easycode_compiler
if %errorlevel% neq 0 (
    echo [ERROR] Failed to compile C code with GCC.
    pause
    exit /b %errorlevel%
)

REM Execute the compiled EasyCode compiler
echo [INFO] Compilation succeeded. Running EasyCode compiler...
easycode_compiler < test_program.txt
if %errorlevel% neq 0 (
    echo [ERROR] Failed to execute the EasyCode compiler.
    pause
    exit /b %errorlevel%
)

echo [INFO] Execution completed successfully.
pause

